# Generated by Django 4.2.11 on 2024-06-25 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=255)),
                ('date_opened', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('monthly_debt', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('current_credit_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('maximum_open_credit', models.IntegerField(blank=True, null=True)),
                ('months_since_last_delinquent', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=128, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=128, null=True)),
                ('credit_score', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('annual_income', models.IntegerField(blank=True, null=True)),
                ('years_in_current_job', models.CharField(blank=True, choices=[('< 1 year', '< 1 year'), ('1 year', '1 year'), ('2 years', '2 years'), ('3 years', '3 years'), ('4 years', '4 years'), ('5 years', '5 years'), ('6 years', '6 years'), ('7 years', '7 years'), ('8 years', '8 years'), ('9 years', '9 years'), ('10+ years', '10+ years')], max_length=20, null=True)),
                ('home_ownership', models.CharField(blank=True, choices=[('Rent', 'Rent'), ('Home Mortgage', 'Home Mortgage'), ('Own Home', 'Own Home'), ('Have Mortgage', 'Have Mortgage'), ('Other', 'Other')], max_length=20, null=True)),
                ('years_of_credit_history', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('number_of_open_accounts', models.IntegerField(blank=True, null=True)),
                ('number_of_credit_problems', models.IntegerField(blank=True, null=True)),
                ('bankruptcies', models.IntegerField(blank=True, null=True)),
                ('tax_liens', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_loan_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('term', models.CharField(choices=[('Short Term', 'Short Term'), ('Long Term', 'Long Term')], max_length=20)),
                ('purpose', models.TextField(max_length=255)),
                ('loan_status', models.CharField(choices=[('Fully Paid', 'Fully Paid'), ('Charged Off', 'Charged Off')], max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.account')),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bank'),
        ),
        migrations.AddField(
            model_name='account',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.customer'),
        ),
    ]
