services:
  db:
    image: postgres:12.7
    restart: always
    environment:
      POSTGRES_DB: prod_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
    volumes:
      - prod_db_volume:/var/lib/postgresql/data

volumes:
  prod_db_volume: