services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: local_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data/

volumes:
  db_volume: