name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        
    - name: Install Dependencies
      env:
        DATABASE_NAME: postgres
        USERNAME: postgres
        PASSWORD: postgres
        HOST: localhost
        PORT: 5432
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py check
        
    - name: Run Tests
      run: |
        python manage.py test --noinput
